### PR TITLE
clickhouse_loader support for RMT with is_deleted

### PR DESCRIPTION
**Pull request by aadant**
- added the option for the deleted column in ReplacingMergeTree
- using ANTLR to parse the MySQL schema

### CODE REVIEW

**Comment by AdamKatzDev** [comment]
@aadant Could you please resolve the conflicts?

**Comment by aadant** [comment]
> @aadant Could you please resolve the conflicts?

Done, it probably needs more testing. Will test it on complex schemas we have in house

**Comment by AdamKatzDev** [comment]
If you can test the `COMMENT` issue then it would be nice. I can also verify the PR on my data but I need a quick start guide for this.

**Comment by aadant** [comment]
@AdamKatzDev  got it working, tested on 400+ schema without errors. Btw do you want to migrate the comment in CH too ?

```
$ python db_load/mysql_parser/mysql_parser.py t.sql
2023-10-12 16:23:04,010 - root - MainThread - INFO - source = create table t(
id int primary key,
created_at datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)')
) engine=InnoDB;

2023-10-12 16:23:04,332 - root - MainThread - INFO - CREATE TABLE t (id int NULL,
created_at datetime NOT NULL,
`_sign` Int8 DEFAULT 1,
`_version` UInt64 DEFAULT 0,
`is_deleted` UInt8 DEFAULT 0
) engine=ReplacingMergeTree(_version,is_deleted)  order by id
2023-10-12 16:23:04,333 - root - MainThread - DEBUG - (sqlStatements (sqlStatement (ddlStatement (createTable create table (tableName (fullId (uid (simpleId t)))) (createDefinitions ( (createDefinition (fullColumnName (uid (simpleId id))) (columnDefinition (dataType int) (columnConstraint primary key))) , (createDefinition (fullColumnName (uid (simpleId created_at))) (columnDefinition (dataType datetime) (columnConstraint (nullNotnull NOT NULL)) (columnConstraint COMMENT '(DC2Type:datetime_immutable)'))) ))))))
2023-10-12 16:23:04,333 - root - MainThread - INFO - target = CREATE TABLE t (id int NULL,
created_at datetime NOT NULL,
`_sign` Int8 DEFAULT 1,
`_version` UInt64 DEFAULT 0,
`is_deleted` UInt8 DEFAULT 0
) engine=ReplacingMergeTree(_version,is_deleted)  order by id
```

This PR used ANTLR for parsing the DDL. It can even convert other DDL. it is a way to test the parser on the command line.

```
python db_load/mysql_parser/mysql_parser.py testk4.sql
2023-10-12 16:19:52,399 - root - MainThread - INFO - source = alter table t1 rename to t2;

2023-10-12 16:19:53,010 - root - MainThread - DEBUG - (sqlStatements (sqlStatement (ddlStatement (alterTable alter table (tableName (fullId (uid (simpleId t1)))) (alterSpecification rename to (uid (simpleId t2)))))) (emptyStatement_ ;))
2023-10-12 16:19:53,010 - root - MainThread - INFO - target =  rename table t1 to t2
```


Possible improvements 

- force the use of the regexp parser for testing it
- migrate the comments
- support partitioned table in the ANTLR parser

**Comment by AdamKatzDev** [comment]
@aadant 
>Btw do you want to migrate the comment in CH too ?

No, not really. It looks like ClickHouse does not support `COMMENT` for fields anyway.

**Comment by aadant** [comment]
> @aadant
> 
> > Btw do you want to migrate the comment in CH too ?
> 
> No, not really. It looks like ClickHouse does not support `COMMENT` for fields anyway.

will add this as an option.

https://clickhouse.com/docs/en/sql-reference/statements/alter/column#comment-column

ultimately we should have a yaml file that controls this migration with overrides

**Review by minguyen9988 — APPROVED** [review]

**Comment by aadant** [comment]
@AdamKatzDev this PR is ready for review.
I loaded a 20G compressed dump into CH with 400+ tables and it worked fine.
@subkanthi please review and merge this !
i will submit more improvements soon

**Comment by AdamKatzDev** [comment]
@aadant 
I've tried to make an import and it failed converting a `json NULL` field. It used to convert it to `Nullable(String)`, but now it just keeps it `json NULL`. ClickHouse can't create the table and writes the following error:
```DB::Exception: Nested type Object('json') cannot be inside Nullable type```

I've tracked the error to these lines: https://github.com/Altinity/clickhouse-sink-connector/blob/dbaee550a18632f27e909d932eb0b486a1598a3e/sink-connector/python/db_load/mysql_parser/CreateTableMySQLParserListener.py#L44-L45


I wish I could fix this as a part of my PR but I could not find any concise documentation for this library to understand what is going on.

**Comment by aadant** [comment]
> @aadant I've tried to make an import and it failed converting a `json NULL` field. It used to convert it to `Nullable(String)`, but now it just keeps it `json NULL`. ClickHouse can't create the table and writes the following error: `DB::Exception: Nested type Object('json') cannot be inside Nullable type`
> 
> I've tracked the error to these lines:
> 
> https://github.com/Altinity/clickhouse-sink-connector/blob/dbaee550a18632f27e909d932eb0b486a1598a3e/sink-connector/python/db_load/mysql_parser/CreateTableMySQLParserListener.py#L44-L45
> 
> I wish I could fix this as a part of my PR but I could not find any concise documentation for this library to understand >what is going on.

thanks for the feedback. The data types supported by the regexp parsers were not fully tested (and you can no longer use it because of the comment). I will create an issue and fix it.

**Comment by aadant** [comment]
Issue created to support all datatypes https://github.com/Altinity/clickhouse-sink-connector/issues/312

**Comment by aadant** [comment]
> I wish I could fix this as a part of my PR but I could not find any concise documentation for this library to understand >what >is going on.

This is standard ANTLR code. The create statement is parsed as an AST and the translation to CH SQL is done by generating the statement from call backs (similar to parsing XML with a SAX parser).

**Pull request merged**
